/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pj_gestion_musique;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author COMPAORÉ Loïc
 */
public class V_Main extends javax.swing.JFrame {

    
    /**
     * Creates new form V_Main
     */
    private Pj_gestion_musique leControl;
     private M_Utilisateur compteConnecte;
    
    public void afficher(){
    
      mn_Parametrage.setVisible(false);
      mi_deconnexion.setVisible(false);
      mn_parametre.setVisible(false);
      this.setLocationRelativeTo(null);
      this.setVisible(true);
    }
       private void connexion() throws SQLException {
        String login, motPasse;

        login = ed_login.getText();
        motPasse = String.valueOf(ed_motpasse.getText());

      
            compteConnecte = leControl.connexion_log(login, motPasse);
            ed_login.setText("henrij");
            ed_motpasse.setText("M2p_Henrij");

            if (compteConnecte == null) {
                lb_Connect.setVisible(true);
                lb_Connect.setForeground(Color.red);
                lb_Connect.setText("Erreur de connexion.");
                mn_Parametrage.setVisible(false);
                mn_parametre.setVisible(false);
                
            } else {
                this.setTitle("Bonjour " + compteConnecte.getLogin());
                    pn_Connexion.setVisible(false);
                if(compteConnecte.getIdRole()==1){
                    mn_Parametrage.setVisible(true);
                    mn_parametre.setVisible(true);
                    mi_utilisateurs.setVisible(true);
                }else{
                    mn_Parametrage.setVisible(true);
                    mn_parametre.setVisible(true);
                    mi_utilisateurs.setVisible(false);
                }
              mi_deconnexion.setVisible(true);
            }
      

    }
    public V_Main(Pj_gestion_musique leControleur) {
        leControl = leControleur;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        pn_Connexion = new javax.swing.JPanel();
        lb_login = new javax.swing.JLabel();
        lb_motpasse = new javax.swing.JLabel();
        ed_login = new javax.swing.JTextField();
        bt_connexion = new javax.swing.JButton();
        lb_Connect = new javax.swing.JLabel();
        ed_motpasse = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_Quitter = new javax.swing.JMenuItem();
        mn_Parametrage = new javax.swing.JMenu();
        mi_utilisateurs = new javax.swing.JMenuItem();
        mi_Styles = new javax.swing.JMenuItem();
        mi_Albums = new javax.swing.JMenuItem();
        mi_artistes = new javax.swing.JMenuItem();
        mn_parametre = new javax.swing.JMenu();
        mn_Compte = new javax.swing.JMenuItem();
        mi_deconnexion = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_login.setText("Login:");

        lb_motpasse.setText("Mot de passe :");

        ed_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ed_loginActionPerformed(evt);
            }
        });

        bt_connexion.setText("Connexion");
        bt_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_connexionActionPerformed(evt);
            }
        });

        lb_Connect.setText("Connecter vous à votre compte:");

        javax.swing.GroupLayout pn_ConnexionLayout = new javax.swing.GroupLayout(pn_Connexion);
        pn_Connexion.setLayout(pn_ConnexionLayout);
        pn_ConnexionLayout.setHorizontalGroup(
            pn_ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ConnexionLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(pn_ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ConnexionLayout.createSequentialGroup()
                        .addComponent(bt_connexion)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_ConnexionLayout.createSequentialGroup()
                        .addComponent(lb_motpasse, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ed_motpasse, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))))
            .addGroup(pn_ConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_ConnexionLayout.createSequentialGroup()
                        .addComponent(lb_Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pn_ConnexionLayout.createSequentialGroup()
                        .addComponent(lb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(ed_login, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pn_ConnexionLayout.setVerticalGroup(
            pn_ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ConnexionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ed_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_ConnexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_motpasse)
                    .addComponent(ed_motpasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(bt_connexion)
                .addGap(23, 23, 23))
        );

        jMenu1.setText("Fichier");

        mi_Quitter.setText("Quitter");
        mi_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_QuitterActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Quitter);

        jMenuBar1.add(jMenu1);

        mn_Parametrage.setText("Paramétrage");

        mi_utilisateurs.setText("Les Utilisateurs");
        mi_utilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_utilisateursActionPerformed(evt);
            }
        });
        mn_Parametrage.add(mi_utilisateurs);

        mi_Styles.setText("Les Styles");
        mi_Styles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_StylesActionPerformed(evt);
            }
        });
        mn_Parametrage.add(mi_Styles);

        mi_Albums.setText("Les Albums");
        mi_Albums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_AlbumsActionPerformed(evt);
            }
        });
        mn_Parametrage.add(mi_Albums);

        mi_artistes.setText("Les Artistes");
        mi_artistes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_artistesActionPerformed(evt);
            }
        });
        mn_Parametrage.add(mi_artistes);

        jMenuBar1.add(mn_Parametrage);

        mn_parametre.setText("Paramètre");

        mn_Compte.setText("Mon Compte");
        mn_Compte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_CompteActionPerformed(evt);
            }
        });
        mn_parametre.add(mn_Compte);

        mi_deconnexion.setText("Déconnexion");
        mi_deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_deconnexionActionPerformed(evt);
            }
        });
        mn_parametre.add(mi_deconnexion);

        jMenuBar1.add(mn_parametre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(pn_Connexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pn_Connexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_AlbumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_AlbumsActionPerformed
        try {
            leControl.aff_V_Albums();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_AlbumsActionPerformed

    private void mi_StylesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_StylesActionPerformed
        try {
            // TODO add your handling code here:
            leControl.aff_V_Style();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_StylesActionPerformed

    private void mi_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_QuitterActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_mi_QuitterActionPerformed

    private void bt_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_connexionActionPerformed
        try {       
            connexion();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_connexionActionPerformed

    private void mi_artistesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_artistesActionPerformed
        try {
            // TODO add your handling code here:
            leControl.aff_V_Artiste();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_artistesActionPerformed

    private void mi_utilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_utilisateursActionPerformed
        try {
            // TODO add your handling code here:
            leControl.aff_V_Utilisateurs_Admin();
        } catch (SQLException ex) {
            Logger.getLogger(V_Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mi_utilisateursActionPerformed

    private void mn_CompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_CompteActionPerformed
        // TODO add your handling code here:
        leControl.aff_Moncompte();
    }//GEN-LAST:event_mn_CompteActionPerformed

    private void mi_deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_deconnexionActionPerformed
        // TODO add your handling code here:
        leControl.deconnexion();
        this.setTitle("Apllication course");
        mn_Parametrage.setVisible(false);
        mi_deconnexion.setVisible(false);
        mn_parametre.setVisible(false);
        pn_Connexion.setVisible(true);
        
    }//GEN-LAST:event_mi_deconnexionActionPerformed

    private void ed_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ed_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ed_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Main(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_connexion;
    private javax.swing.JTextField ed_login;
    private javax.swing.JPasswordField ed_motpasse;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lb_Connect;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_motpasse;
    private javax.swing.JMenuItem mi_Albums;
    private javax.swing.JMenuItem mi_Quitter;
    private javax.swing.JMenuItem mi_Styles;
    private javax.swing.JMenuItem mi_artistes;
    private javax.swing.JMenuItem mi_deconnexion;
    private javax.swing.JMenuItem mi_utilisateurs;
    private javax.swing.JMenuItem mn_Compte;
    private javax.swing.JMenu mn_Parametrage;
    private javax.swing.JMenu mn_parametre;
    private javax.swing.JPanel pn_Connexion;
    // End of variables declaration//GEN-END:variables
}
