/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.pj_gestion_musique;

import java.awt.Color;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author COMPAORÉ Loïc
 */
public class V_Style extends javax.swing.JDialog {

    /**
     * Creates new form V_Style
     */
    
    private Pj_gestion_musique leControl;
    private LinkedHashMap<Integer, M_Style> lesStyles;
    private M_Style unStyle;
    private DefaultTableModel dm_tb_Styles;
    private int ligne, nbStyles, ligneSelect;
    private Integer uneCle;
    private char  mode;
    public void afficher(LinkedHashMap<Integer, M_Style> lesStyles){
    this.lesStyles = lesStyles;
    dm_tb_Styles = (DefaultTableModel) tb_Style.getModel();
        
        ligne = 0;
        nbStyles = lesStyles.size();
        dm_tb_Styles.setRowCount(nbStyles);
        
        
        for (Integer uneCle : lesStyles.keySet()){
            unStyle = this.lesStyles.get(uneCle);
            tb_Style.setValueAt(unStyle.getIdStyle(), ligne, 0);
            tb_Style.setValueAt(unStyle.getLibelle(), ligne, 1);
            ligne++;
        }
       tb_Style.clearSelection();
        
        this.setSize(450, 350);
        this.setLocationRelativeTo(null);
        pn_CMS_Styles.setBounds(15, 15, 400, 300);
        pn_Saisie_Styles.setBounds(15, 15, 400, 400);
        pn_CMS_Styles.setVisible(true);
        pn_Saisie_Styles.setVisible(false);

    this.setVisible(true);
    }
    
    private void affichePanel(boolean mode){
        //true pour afficher le tableau
        //false pour le panel de saisie
        pn_Saisie_Styles.setVisible(!mode);
        pn_CMS_Styles.setVisible(mode);
    }
    public V_Style(java.awt.Frame parent, boolean modal,Pj_gestion_musique leControleur) {
        super(parent, modal);
         leControl = leControleur;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_CMS_Styles = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Style = new javax.swing.JTable();
        bt_Modifier = new javax.swing.JButton();
        bt_Ajouter = new javax.swing.JButton();
        bt_supprimer = new javax.swing.JButton();
        lb_Selection = new javax.swing.JLabel();
        pn_Saisie_Styles = new javax.swing.JPanel();
        ed_Libelle = new javax.swing.JTextField();
        bt_Enregistrer = new javax.swing.JButton();
        bt_Annuler = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_fermer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);

        tb_Style.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id Style", "Libéllé du Style"
            }
        ));
        tb_Style.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb_Style.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_StyleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Style);

        bt_Modifier.setText("Modifier");
        bt_Modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModifierActionPerformed(evt);
            }
        });

        bt_Ajouter.setText("Ajouter");
        bt_Ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AjouterActionPerformed(evt);
            }
        });

        bt_supprimer.setText("Supprimer");
        bt_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerActionPerformed(evt);
            }
        });

        lb_Selection.setText("Sélectionner un Style:");

        javax.swing.GroupLayout pn_CMS_StylesLayout = new javax.swing.GroupLayout(pn_CMS_Styles);
        pn_CMS_Styles.setLayout(pn_CMS_StylesLayout);
        pn_CMS_StylesLayout.setHorizontalGroup(
            pn_CMS_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CMS_StylesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_CMS_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_CMS_StylesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(pn_CMS_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_Ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lb_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        pn_CMS_StylesLayout.setVerticalGroup(
            pn_CMS_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_CMS_StylesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lb_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_CMS_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pn_CMS_StylesLayout.createSequentialGroup()
                        .addComponent(bt_Modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Ajouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_supprimer)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        bt_Enregistrer.setText("Enregistrer");
        bt_Enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EnregistrerActionPerformed(evt);
            }
        });

        bt_Annuler.setText("Annuler");
        bt_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_Saisie_StylesLayout = new javax.swing.GroupLayout(pn_Saisie_Styles);
        pn_Saisie_Styles.setLayout(pn_Saisie_StylesLayout);
        pn_Saisie_StylesLayout.setHorizontalGroup(
            pn_Saisie_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Saisie_StylesLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pn_Saisie_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_Saisie_StylesLayout.createSequentialGroup()
                        .addComponent(bt_Enregistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(bt_Annuler)
                        .addGap(59, 59, 59))
                    .addGroup(pn_Saisie_StylesLayout.createSequentialGroup()
                        .addComponent(ed_Libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pn_Saisie_StylesLayout.setVerticalGroup(
            pn_Saisie_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_Saisie_StylesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ed_Libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pn_Saisie_StylesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Enregistrer)
                    .addComponent(bt_Annuler))
                .addContainerGap())
        );

        jMenu1.setText("Fichier");

        mi_fermer.setText("Quitter");
        mi_fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_fermerActionPerformed(evt);
            }
        });
        jMenu1.add(mi_fermer);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_CMS_Styles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_Saisie_Styles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_CMS_Styles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_Saisie_Styles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AjouterActionPerformed
        // TODO add your handling code here:
        ed_Libelle.setText("");
        this.affichePanel(false);
        mode ='A';
    }//GEN-LAST:event_bt_AjouterActionPerformed

    private void bt_EnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EnregistrerActionPerformed
        // TODO add your handling code here:
         switch(mode){
            case 'M':   ligneSelect = tb_Style.getSelectedRow();
                        uneCle = (Integer) tb_Style.getValueAt(ligneSelect,0);
             {
                 try {
                     leControl.modif_Style(uneCle,ed_Libelle.getText());
                 } catch (SQLException ex) {
                     Logger.getLogger(V_Style.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }
                        break;

            case 'A':   
             {
                 try {
                     leControl.ajout_Style(ed_Libelle.getText());
                 } catch (SQLException ex) {
                     Logger.getLogger(V_Style.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }

            }
    }//GEN-LAST:event_bt_EnregistrerActionPerformed

    private void bt_ModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModifierActionPerformed
        // TODO add your handling code here:
        ligneSelect = tb_Style.getSelectedRow();
        if(ligneSelect == -1 ){
            lb_Selection.setForeground(Color.RED);
        }
        else {
            this.affichePanel(false);
            uneCle = (Integer) tb_Style.getValueAt(ligneSelect,0);
            unStyle= lesStyles.get(uneCle);
            ed_Libelle.setText(unStyle.getLibelle());
            mode = 'M';
        }
    }//GEN-LAST:event_bt_ModifierActionPerformed

    private void bt_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerActionPerformed
        try {
            // TODO add your handling code here:
            
            ligneSelect = tb_Style.getSelectedRow();
        uneCle = (Integer) tb_Style.getValueAt(ligneSelect,0);
            
            if (leControl.estLiee(uneCle)){
                JOptionPane.showMessageDialog(this, "La suppression du Style n'est pas possible car il existe au moins un Album lié à ce Style", "Suppression impossible", 0);
            }
            else {
                ligneSelect = tb_Style.getSelectedRow();
                uneCle = (Integer) tb_Style.getValueAt(ligneSelect,0);
                int dialogResult = JOptionPane.showConfirmDialog (this, "Etes-vous sûre de vouloir supprimer le Style "+ed_Libelle.getText()+" ?","Warning",JOptionPane.YES_NO_OPTION);
                if(dialogResult == JOptionPane.YES_OPTION){
                    try {
                        leControl.sup_Style(uneCle);
                    } catch (SQLException ex) {
                        Logger.getLogger(V_Style.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(V_Style.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_supprimerActionPerformed

    private void tb_StyleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_StyleMouseClicked
        // TODO add your handling code here:
        lb_Selection.setForeground(Color.BLACK);
    }//GEN-LAST:event_tb_StyleMouseClicked

    private void bt_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AnnulerActionPerformed
        // TODO add your handling code here
        this.affichePanel(true);
    }//GEN-LAST:event_bt_AnnulerActionPerformed

    private void mi_fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_fermerActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_mi_fermerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Style.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Style.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Style.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Style.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                V_Style dialog = new V_Style(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Ajouter;
    private javax.swing.JButton bt_Annuler;
    private javax.swing.JButton bt_Enregistrer;
    private javax.swing.JButton bt_Modifier;
    private javax.swing.JButton bt_supprimer;
    private javax.swing.JTextField ed_Libelle;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Selection;
    private javax.swing.JMenuItem mi_fermer;
    private javax.swing.JPanel pn_CMS_Styles;
    private javax.swing.JPanel pn_Saisie_Styles;
    private javax.swing.JTable tb_Style;
    // End of variables declaration//GEN-END:variables
}
